### ISSUE TITLE
Split update and processing of data sources

### ISSUE THREAD

**Issue by AstrorEnales** [AstrorEnales/BioDWH2#1]
For data sources that can't be updated automatically, we need an information from the updater to manually download the files and put them in the correct location. Additionally, the update time and new version number somehow need to be put into the metadata.json for the data sources.

Therefore, the parsing and exporting, etc. need to be seperated into an additional cli parameter.

**Comment by LenaRaupach** [comment]
If not every data source can be updated automatically, the instruction to download and to add the data manually appears as logger information. 
To integrate the data, the command line has to contain the following: 
BioDWH2.jar -i /path/to/Workspace [sourceName] [version] 

The [sourceName] has to be be one of the data source set, e.g. {dgidb, drugbank, hgnc, medrt, ndfrt}. The source data has to be moved manually to the workspace folder.
